name: Image build

env:
  ONLINE_REGISTER: ghcr.io
  ONLINE_REGISTER_USER: ${{ github.actor }}
  BUILD_PLATFORM: linux/amd64,linux/arm64
  ONLINE_REGISTER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}

on:
  push:
    branch:
      - main
  workflow_call:
    inputs:
      ref:
        required: true
        type: string
      tag:
        required: false
        type: string
      push:
        required: false
        type: boolean

permissions: write-all

jobs:
  build-image:
    name: Image build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Get Image Push
        id: tag
        run: |
          if ${{ inputs.ref != '' }} ; then
            echo "call by workflow_call"
            echo ::set-output name=tag::${{ inputs.ref }}
            echo ::set-output name=version::${{ inputs.ref }}
            echo ::set-output name=push::${{ inputs.push }}
          elif ${{ github.event_name == 'push' }} ; then
            echo "trigger by push"
            echo ::set-output name=tag::${{ github.sha }}
            echo ::set-output name=version::"latest"
            echo ::set-output name=push::true
          elif ${{ github.event_name == 'pull_request_target' }} ; then
            echo "trigger by pull_request_target"
            echo ::set-output name=tag::${{ github.event.pull_request.head.sha }}
            echo ::set-output name=version::latest
            echo ::set-output name=push::false
          else
            echo "unexpected event: ${{ github.event_name }}"
            exit 1
          fi

      - name: Getting Build Arg
        id: arg
        continue-on-error: false
        run: |
          GIT_COMMIT_VERSION=$( git show -s --format='format:%H')
          GIT_COMMIT_TIME=$( git show -s --format='format:%aI')
          echo ::set-output name=commitver::${GIT_COMMIT_VERSION}
          echo ::set-output name=committime::${GIT_COMMIT_TIME}

      - name: Login to online register
        uses: docker/login-action@v2.0.0
        if: ${{ steps.tag.outputs.push == 'true' }}
        with:
          username: ${{ env.ONLINE_REGISTER_USER }}
          password: ${{ env.ONLINE_REGISTER_PASSWORD }}
          registry: ${{ env.ONLINE_REGISTER }}

      - name: Build container image and push
        if: ${{ steps.tag.outputs.push == 'true' }}
        uses: docker/build-push-action@v2
        with:
          context: ./
          push: true
          tags: ghcr.io/${{ github.repository }}/meta-plugins:${{ steps.tag.outputs.version }}
          file: ./images/Dockerfile
          github-token: ${{ secrets.WELAN_PAT }}
          platforms: ${{ env.BUILD_PLATFORM }}
          build-args: |
            GIT_COMMIT_VERSION=${{ steps.arg.outputs.commitver }}
            GIT_COMMIT_TIME=${{ steps.arg.outputs.committime }}
            VERSION=${{ steps.tag.outputs.tag }}

      - name: Build ci container image for e2e-test
        if: ${{ steps.tag.outputs.push != 'true' }}
        uses: docker/build-push-action@v2
        with:
          context: ./
          push: false
          tags: ghcr.io/${{ github.repository }}/meta-plugins-ci:${{ steps.tag.outputs.version }}
          file: ./images/Dockerfile
          github-token: ${{ secrets.GITHUB_TOKEN }}
          platforms: linux/amd64
          outputs: type=docker
          build-args: |
            GIT_COMMIT_VERSION=${{ steps.arg.outputs.commitver }}
            GIT_COMMIT_TIME=${{ steps.arg.outputs.committime }}
            VERSION=${{ steps.tag.outputs.tag }}

      - name: Scan Image
        if: ${{ steps.tag.outputs.push != 'true' }}
        run: |
          docker images
          docker save -o /tmp/ci-images.tar ghcr.io/${{ github.repository }}/meta-plugins-ci:latest
          make lint_image_trivy -e IMAGE_NAME=ghcr.io/${{ github.repository }}/meta-plugins-ci:latest

      - name: Upload artifact e2e image tar
        if: ${{ steps.tag.outputs.push != 'true' }}
        uses: actions/upload-artifact@v3.1.0
        with:
          name: image-e2e-tar
          path: /tmp/ci-images.tar
          retention-days: 1
