name: Update Badge

env:
  CODESTATUSSCRIPT: "./hack/scripts/codeCoverage.sh"
  E2ESTATUSSCRIPT: "./hack/scripts/e2ecover.sh"
  TODOSCRIPT: "./hack/scripts/todocover.sh"

on:
  push:
    branches:
      - main

jobs:
  update-badges:
    name: Update Badges
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Download cloc
        run: sudo apt-get update -y && sudo apt-get install -y cloc

      - name: Get the Numbers
        shell: bash
        run: |
          TOOL_PATH=${{ env.CODESTATUSSCRIPT }}
          COMMENT_PERCENTAGE=$(  ${TOOL_PATH} --comment-percent )
          CODE_LINES=$(  ${TOOL_PATH} --code-lines )
          echo "CODE_LINES=${CODE_LINES}" >> $GITHUB_ENV
          TOOL_PATH=${{ env.TODOSCRIPT }}
          TODO_STATUS=$( ${TOOL_PATH} )
          echo "TODO_STATUS=${TODO_STATUS}" >> $GITHUB_ENV
          echo "COMMENT_PERCENTAGE=${COMMENT_PERCENTAGE}" >> $GITHUB_ENV

      - name: Create Lines-of-Code-Badge
        uses: schneegans/dynamic-badges-action@v1.6.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: 6b05882662346c2592a432226bf3d249
          filename: code-lines.json
          label: Code Lines
          message: ${{ env.CODE_LINES }}
          color: lightgrey

      - name: Create TODO-Badge
        uses: schneegans/dynamic-badges-action@v1.6.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: 82aa5e4487e1870aa206c1d713429345
          filename: todo.json
          label: todo
          message: ${{ env.TODO_STATUS }}
          color: lightgrey

      - name: Create Comments-Badge
        uses: schneegans/dynamic-badges-action@v1.6.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: 92ef1f04e61af8f8b970c0b15f51c7a8
          filename: comment.json
          label: Comments
          message: ${{ env.COMMENT_PERCENTAGE }}%
          valColorRange: ${{ env.COMMENT_PERCENTAGE }}
          maxColorRange: 100
          minColorRange: 0
